export const TABLE_ELEMENT_DEFAULT_STYLE: string =
  "TABLE_ELEMENT_DEFAULT_STYLE";
export const TABLE_ELEMENT_ON_GOING_STYLE: string =
  "TABLE_ELEMENT_ON_GOING_STYLE";
export const TABLE_ELEMENT_SUCCESS_STYLE: string =
  "TABLE_ELEMENT_SUCCESS_STYLE";
export const TABLE_ELEMENT_ERROR_STYLE: string = "TABLE_ELEMENT_ERROR_STYLE";
export const TABLE_ELEMENT_INDICATE_STYLE: string =
  "TABLE_ELEMENT_INDICATE_STYLE";
export const TABLE_ELEMENT_DISABLE_STYLE: string =
  "TABLE_ELEMENT_DISABLE_STYLE";
