export const TABLE_ELEMENT_DEFAULT_STYLE = "TABLE_ELEMENT_DEFAULT_STYLE";
export const TABLE_ELEMENT_ON_GOING_STYLE = "TABLE_ELEMENT_ON_GOING_STYLE";
export const TABLE_ELEMENT_SUCCESS_STYLE = "TABLE_ELEMENT_SUCCESS_STYLE";
export const TABLE_ELEMENT_ERROR_STYLE = "TABLE_ELEMENT_ERROR_STYLE";
export const TABLE_ELEMENT_INDICATE_STYLE = "TABLE_ELEMENT_INDICATE_STYLE";
export const TABLE_ELEMENT_SUB_INDICATE_STYLE =
  "TABLE_ELEMENT_SUB_INDICATE_STYLE";
export const TABLE_ELEMENT_DISABLE_STYLE = "TABLE_ELEMENT_DISABLE_STYLE";
export const TABLE_ELEMENT_HELPER_STYLE = "TABLE_ELEMENT_HELPER_STYLE";
export const TABLE_ELEMENT_HELPER_STYLE_TWO = "TABLE_ELEMENT_HELPER_STYLE_TWO";
export const TABLE_ELEMENT_HELPER_STYLE_THREE =
  "TABLE_ELEMENT_HELPER_STYLE_THREE";
