const days = [
  "sunday",
  "saturday",
  "friday",
  "thursday",
  "wensday",
  "tuesday",
  "monday"
];

const fruits = [
  "Apple",
  "Apricot",
  "Avocado",
  "Banana",
  "Bilberry",
  "Blackberry",
  "Blackcurrant",
  "Blueberry",
  "Boysenberry",
  "Crab apples",
  "Currant",
  "Cherry",
  "Cherimoya",
  "Chico",
  "Cloudberry",
  "Coconut",
  "Cranberry",
  "Cucumber",
  "Custard",
  "Damson",
  "Date",
  "Dragonfruit",
  "Durian",
  "Elderberry",
  "Feijoa",
  "Fig",
  "Goji",
  "Gooseberry",
  "Grape",
  "Raisin",
  "Grapefruit",
  "Guava",
  "Honeyberry",
  "Huckleberry",
  "Jabuticaba",
  "Jackfruit",
  "Jambul",
  "Jujube",
  "Juniper",
  "Kiwano",
  "Kiwifruit",
  "Kumquat",
  "Lemon",
  "Lime",
  "Loquat",
  "Longan",
  "Lychee",
  "Mango",
  "Mangosteen",
  "Marionberry",
  "Melon",
  "Cantaloupe",
  "Honeydew",
  "Watermelon",
  "Miracle",
  "Mulberry",
  "Nectarine",
  "Nance",
  "Olive",
  "Orange",
  "Blood",
  "Clementine",
  "Mandarine",
  "Tangerine",
  "Papaya",
  "Passionfruit",
  "Peach",
  "Pear",
  "Persimmon",
  "Plantain",
  "Plum",
  "Prune",
  "Pineapple",
  "Plumcot",
  "Pomegranate",
  "Pomelo",
  "Purple",
  "Quince",
  "Raspberry",
  "Salmonberry",
  "Rambutan",
  "Redcurrant",
  "Salal",
  "Salak",
  "Satsuma",
  "Soursop",
  "Star",
  "Solanum",
  "Strawberry",
  "Tamarillo",
  "Tamarind",
  "Ugli",
  "Yuzu"
];

const randomInt = max => Math.floor(Math.random() * max);
const randomFruit = () => fruits[randomInt(fruits.length)];
const randomDay = () => days[randomInt(days.length)];
const result = (word1, word2) => ({ word1: word1, word2: word2 });
const randomDays = () => result(randomDay(), randomDay());
const randomFruits = () => result(randomFruit(), randomFruit());

export default () => {
  const mod = Math.floor(fruits.length / days.length) + 1;
  const total = fruits.length + days.length;
  return randomInt(total) % mod === 0 ? randomDays() : randomFruits();
};
